import figlet, { type Fonts, type Options } from "figlet";

export const useFiglet = () => {
  figlet.defaults({ fontPath: "//unpkg.com/figlet@1.6.0/fonts/" });
  const getAllFonts = () => {
    return Object.keys(fontsObj) as Fonts[];
  };
  const text = async (val: string, options: Options) => {
    return await new Promise<string>((resolve, reject) =>
      figlet.text(
        val,
        {
          ...options,
        },
        (err, text) => {
          if (err) {
            reject(err);
            return;
          }
          resolve(text ?? "");
        }
      )
    );
  };

  return {
    getAllFonts,
    text,
  };
};

const fontsObj: Record<Fonts, undefined> = {
  "1Row": undefined,
  "3-D": undefined,
  "3D Diagonal": undefined,
  "3D-ASCII": undefined,
  "3x5": undefined,
  "4Max": undefined,
  "5 Line Oblique": undefined,
  "AMC 3 Line": undefined,
  "AMC 3 Liv1": undefined,
  "AMC AAA01": undefined,
  "AMC Neko": undefined,
  "AMC Razor": undefined,
  "AMC Razor2": undefined,
  "AMC Slash": undefined,
  "AMC Slider": undefined,
  "AMC Thin": undefined,
  "AMC Tubes": undefined,
  "AMC Untitled": undefined,
  "ANSI Regular": undefined,
  "ANSI Shadow": undefined,
  "ASCII New Roman": undefined,
  Acrobatic: undefined,
  Alligator: undefined,
  Alligator2: undefined,
  Alpha: undefined,
  Alphabet: undefined,
  Arrows: undefined,
  Avatar: undefined,
  B1FF: undefined,
  Banner: undefined,
  "Banner3-D": undefined,
  Banner3: undefined,
  Banner4: undefined,
  Barbwire: undefined,
  Basic: undefined,
  Bear: undefined,
  Bell: undefined,
  Benjamin: undefined,
  "Big Chief": undefined,
  "Big Money-ne": undefined,
  "Big Money-nw": undefined,
  "Big Money-se": undefined,
  "Big Money-sw": undefined,
  Big: undefined,
  Bigfig: undefined,
  Binary: undefined,
  Block: undefined,
  Blocks: undefined,
  Bloody: undefined,
  Bolger: undefined,
  Braced: undefined,
  Bright: undefined,
  "Broadway KB": undefined,
  Broadway: undefined,
  Bubble: undefined,
  Bulbhead: undefined,
  Caligraphy: undefined,
  Caligraphy2: undefined,
  "Calvin S": undefined,
  Cards: undefined,
  Catwalk: undefined,
  Chiseled: undefined,
  Chunky: undefined,
  Coinstak: undefined,
  Cola: undefined,
  Colossal: undefined,
  Computer: undefined,
  Contessa: undefined,
  Contrast: undefined,
  Cosmike: undefined,
  Crawford: undefined,
  Crawford2: undefined,
  Crazy: undefined,
  Cricket: undefined,
  Cursive: undefined,
  Cyberlarge: undefined,
  Cybermedium: undefined,
  Cybersmall: undefined,
  Cygnet: undefined,
  DANC4: undefined,
  "DOS Rebel": undefined,
  DWhistled: undefined,
  "Dancing Font": undefined,
  Decimal: undefined,
  "Def Leppard": undefined,
  "Delta Corps Priest 1": undefined,
  Diamond: undefined,
  "Diet Cola": undefined,
  Digital: undefined,
  Doh: undefined,
  Doom: undefined,
  "Dot Matrix": undefined,
  "Double Shorts": undefined,
  Double: undefined,
  "Dr Pepper": undefined,
  "Efti Chess": undefined,
  "Efti Font": undefined,
  "Efti Italic": undefined,
  "Efti Piti": undefined,
  "Efti Robot": undefined,
  "Efti Wall": undefined,
  "Efti Water": undefined,
  Electronic: undefined,
  Elite: undefined,
  Epic: undefined,
  Fender: undefined,
  Filter: undefined,
  "Fire Font-k": undefined,
  "Fire Font-s": undefined,
  Flipped: undefined,
  "Flower Power": undefined,
  "Four Tops": undefined,
  Fraktur: undefined,
  "Fun Face": undefined,
  "Fun Faces": undefined,
  Fuzzy: undefined,
  Georgi16: undefined,
  Georgia11: undefined,
  Ghost: undefined,
  Ghoulish: undefined,
  Glenyn: undefined,
  Goofy: undefined,
  Gothic: undefined,
  Graceful: undefined,
  Gradient: undefined,
  Graffiti: undefined,
  Greek: undefined,
  "Heart Left": undefined,
  "Heart Right": undefined,
  "Henry 3D": undefined,
  Hex: undefined,
  Hieroglyphs: undefined,
  Hollywood: undefined,
  "Horizontal Left": undefined,
  "Horizontal Right": undefined,
  "ICL-1900": undefined,
  Impossible: undefined,
  Invita: undefined,
  Isometric1: undefined,
  Isometric2: undefined,
  Isometric3: undefined,
  Isometric4: undefined,
  Italic: undefined,
  Ivrit: undefined,
  "JS Block Letters": undefined,
  "JS Bracket Letters": undefined,
  "JS Capital Curves": undefined,
  "JS Cursive": undefined,
  "JS Stick Letters": undefined,
  Jacky: undefined,
  Jazmine: undefined,
  Jerusalem: undefined,
  Katakana: undefined,
  Kban: undefined,
  Keyboard: undefined,
  Knob: undefined,
  "Konto Slant": undefined,
  Konto: undefined,
  LCD: undefined,
  "Larry 3D 2": undefined,
  "Larry 3D": undefined,
  Lean: undefined,
  Letters: undefined,
  "Lil Devil": undefined,
  "Line Blocks": undefined,
  Linux: undefined,
  Lockergnome: undefined,
  Madrid: undefined,
  Marquee: undefined,
  Maxfour: undefined,
  Merlin1: undefined,
  Merlin2: undefined,
  Mike: undefined,
  Mini: undefined,
  Mirror: undefined,
  Mnemonic: undefined,
  Modular: undefined,
  Morse: undefined,
  Morse2: undefined,
  Moscow: undefined,
  Mshebrew210: undefined,
  Muzzle: undefined,
  NScript: undefined,
  "NT Greek": undefined,
  "NV Script": undefined,
  "Nancyj-Fancy": undefined,
  "Nancyj-Improved": undefined,
  "Nancyj-Underlined": undefined,
  Nancyj: undefined,
  Nipples: undefined,
  O8: undefined,
  OS2: undefined,
  Octal: undefined,
  Ogre: undefined,
  "Old Banner": undefined,
  Pagga: undefined,
  "Patorjk's Cheese": undefined,
  "Patorjk-HeX": undefined,
  Pawp: undefined,
  "Peaks Slant": undefined,
  Peaks: undefined,
  Pebbles: undefined,
  Pepper: undefined,
  Poison: undefined,
  Puffy: undefined,
  Puzzle: undefined,
  Pyramid: undefined,
  Rammstein: undefined,
  Rectangles: undefined,
  "Red Phoenix": undefined,
  Relief: undefined,
  Relief2: undefined,
  Reverse: undefined,
  Roman: undefined,
  Rot13: undefined,
  Rotated: undefined,
  Rounded: undefined,
  "Rowan Cap": undefined,
  Rozzo: undefined,
  Runic: undefined,
  Runyc: undefined,
  "S Blood": undefined,
  "SL Script": undefined,
  "Santa Clara": undefined,
  Script: undefined,
  Serifcap: undefined,
  Shadow: undefined,
  Shimrod: undefined,
  Short: undefined,
  "Slant Relief": undefined,
  Slant: undefined,
  Slide: undefined,
  "Small Caps": undefined,
  "Small Isometric1": undefined,
  "Small Keyboard": undefined,
  "Small Poison": undefined,
  "Small Script": undefined,
  "Small Shadow": undefined,
  "Small Slant": undefined,
  "Small Tengwar": undefined,
  Small: undefined,
  Soft: undefined,
  Speed: undefined,
  Spliff: undefined,
  Stacey: undefined,
  Stampate: undefined,
  Stampatello: undefined,
  Standard: undefined,
  "Star Strips": undefined,
  "Star Wars": undefined,
  Stellar: undefined,
  Stforek: undefined,
  "Stick Letters": undefined,
  Stop: undefined,
  Straight: undefined,
  "Stronger Than All": undefined,
  "Sub-Zero": undefined,
  "Swamp Land": undefined,
  Swan: undefined,
  Sweet: undefined,
  THIS: undefined,
  Tanja: undefined,
  Tengwar: undefined,
  Term: undefined,
  Test1: undefined,
  "The Edge": undefined,
  Thick: undefined,
  Thin: undefined,
  Thorned: undefined,
  "Three Point": undefined,
  "Ticks Slant": undefined,
  Ticks: undefined,
  Tiles: undefined,
  "Tinker-Toy": undefined,
  Tombstone: undefined,
  Train: undefined,
  Trek: undefined,
  Tsalagi: undefined,
  Tubular: undefined,
  Twisted: undefined,
  "Two Point": undefined,
  "USA Flag": undefined,
  Univers: undefined,
  Varsity: undefined,
  Wavy: undefined,
  Weird: undefined,
  "Wet Letter": undefined,
  Whimsy: undefined,
  Wow: undefined,
};
